# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bf96855058c45271443040712f7cc849e83e8d9397769d1d7b4737b967808d2d3efe830518b9838f7b6c67fde3c2b24664d068caa9123488942f47d4275402a

test:
  secret_key_base: 8e823cae8cd2ed2b38eaeb04475944df731f3cb350a7c25d79e6c143da2c5a720a4af2015b4b4a95e1158b09c7f36e6a1f3f85c7df1464a1c6fcdf967643b5ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
